name: admin

on:
  pull_request:
    paths:
      - ".github/workflows/admin.yml"
      - "admin/**"
      - "rustsec/**"
      - "Cargo.*"
  push:
    branches: main

defaults:
  run:
    working-directory: cargo-audit

env:
  RUSTFLAGS: -D warnings
  RUSTDOCFLAGS: -D warnings

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: rustsec/rust-cache@v1
      - run: cargo test
